### PR TITLE
Add support for older node versions

### PR DESCRIPTION
**Pull request by steelbrain**
Add support for older Node.js versions to avoid failures similar to

- https://travis-ci.org/steelbrain/intentions/jobs/150741259
- https://travis-ci.org/steelbrain/intentions/jobs/150741261

Both use APM's bundled Node.js versions that consumers can't easily change, changing this module is a good direction IMHO :)

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Use `strip-bom@2.0.0` if you want support for older versions.

**Comment by steelbrain** [comment]
@SamVerschueren I like how you closed it without even a discussion that changing just a few chars saves you from modifying your CI script for each project that has a deep dependency on `strip-bom` and reinstall the 2.0 version.
cc @sindresorhus

**Comment by alexindigo** [comment]
@SamVerschueren Using `strip-bom@2.0.0` makes analysis tools unhappy: error

@steelbrain You might want to look at [stripbom](https://www.npmjs.com/package/stripbom), which is compatible all the way back to node@0.10. :)

**Comment by steelbrain** [comment]
@alexindigo Thanks man, but my packages are not using this package directly. This package is just a deep dependency, and the only dependency that fails :(

I cannot change deep dependencies, and even for changing their versions I'll have to do something like
```
rm -rf node_modules/strip-bom
npm install strip-bom@2.x
```
instead of just changing the syntax to es2015 compatible :\ which even in chars diff is less than the commands 😕

**Comment by SamVerschueren** [comment]
Sorry, didn't meant to be rude. I see that it's ESLint whose failing. It was reported in the ESLint repository [here](https://github.com/eslint/eslint/issues/6679). From that conversation:

> ESLint v3.0.0 now requires Node.js 4 or higher. Going forward, our plan is always to support the LTS version of Node.js and periodically end-of-life support for older Node.js versions. As both Node.js v0.10 and v0.12 will be out of maintenance mode at the end of 2016, we hope that this change won’t affect too many users.
> 
> If you still need ESLint to run on Node.js < 4, then we recommend staying with ESLint v2.13.1 until you are ready to upgrade your Node.js version.

We are upgrading all the libraries and start dropping support for Node.js <4. It is defined in [package.json](https://github.com/sindresorhus/strip-bom/blob/master/package.json#L13) as well and packages that use `eslint@3.0.0` are (and should be) targetting Node.js >= 4 as well. See the discussion in the ESLint repository.

These are just my words (and thoughts) off course. I'm sure @sindresorhus will chime in on the discussion.

**Comment by alexindigo** [comment]
Yeah, deep dependencies are pain. Good luck here.

**Comment by sindresorhus** [comment]
What @SamVerschueren said. You're barking up the wrong tree. ESLint is the one that decided to drop Node.js 0.10/0.12 support and upgrade to v3 of this module.

**Pull request closed without merging**
