### PR TITLE
Restore node 0.10/0.12 support

### PR DESCRIPTION
**Pull request by phated**
Submitted as per https://twitter.com/sindresorhus/status/786035215919517696

### CODE REVIEW

**Comment by alexindigo** [comment]
Would be nice to see it landed, but if not there is one with 0.10 support: https://www.npmjs.com/package/stripbom :)

**Comment by mathiasbynens** [comment]
Wait, what? Why not use an older version if you need 0.12 support?

**Comment by phated** [comment]
Because `npm outdated` exists and is used by many users. Fielding those requests is frustrating for maintainers. The arrow function isn't adding anything to this module.

**Comment by alexindigo** [comment]
And things like bithound.com would complain and mark your package as "needed attention" which will distract from the real issues.

**Comment by phated** [comment]
@mathiasbynens also, the implementation changed when it broke 0.10/0.12 support so what if we want that?

**Comment by phated** [comment]
@sindresorhus ping

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in reversing this. Just use an older version if you need 0.10/0.12 compatibility. Most modules are moving on. This will soon not be the only module that you'll not be able to upgrade.

**Comment by phated** [comment]
If your modules are done, why did you make this change? More importantly, why did you make it with other __actual__ changes? You could have easily broken them into 2 separate semver releases (and still can).

**Comment by sindresorhus** [comment]
I did two breaking changes in the current major release. First, was to break the buffer part into a separate module so there would be one less dependency here. Second, since it was already a breaking change, I took advantage of it and moved to require Node.js 4.

It's clear we see things differently. I'm not really interested in discussing this any further though.

**Pull request closed without merging**
